# Generated by Django 5.2.4 on 2025-07-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='x_coord',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='y_coord',
            field=models.IntegerField(default=0),
        ),
    ]
